platform :ios, '7.0'


pod 'JSONKit', podspec: '~/Desktop/Projects/Personal/watermark-maker/WatermarkMaker/CustomPodSpecs'
pod 'AFNetworking', '1.3.3'
pod 'GPUImage', '0.1.2'
pod 'MBProgressHUD', '0.8'
pod 'CLSideMenu', '0.0.1'
pod 'HMSideMenu', '1.1.0'
pod 'PixateFreestyle', '2.1.2'
pod 'TestFlightSDK', '3.0.0'
pod 'libextobjc', '0.4'
pod 'SEQBImagePickerController', '0.0.1'
pod 'DLAlertView', '1.1.1'
pod 'Color-Picker-for-iOS', '0.1.1'
pod 'UITintedButton', podspec: '~/Desktop/Projects/Personal/watermark-maker/WatermarkMaker/CustomPodSpecs'

